# Generated by Django 3.1.4 on 2020-12-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered',
            old_name='confirm_password',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='email',
        ),
        migrations.AlterField(
            model_name='registered',
            name='password',
            field=models.EmailField(max_length=120),
        ),
    ]
