# Generated by Django 3.1.4 on 2020-12-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201227_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
