# Generated by Django 3.1.4 on 2020-12-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_registered_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
