# Generated by Django 3.1.4 on 2020-12-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201227_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
