# Generated by Django 3.1.4 on 2020-12-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201227_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered',
            old_name='email',
            new_name='_email',
        ),
    ]
