# Generated by Django 3.1.4 on 2020-12-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201228_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered',
            old_name='name',
            new_name='username',
        ),
    ]
