# Generated by Django 3.1.4 on 2020-12-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201231_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registered',
        ),
    ]
